In [48]:
import pieces as p
import numpy as np
import matplotlib.pyplot as plt

In [54]:
# sample 5x5 grid
grid = np.array([np.random.randint(0,2,10) for _ in range(10)], dtype=int)

In [30]:
# sample l2 & ln2 piece
l3 = np.array([[1, 0, 0],
               [1, 0, 0],
               [1, 1, 1]])
l3x = l3.shape[0]
l3y= l3.shape[1]
print("Rows: {}, Cols: {}".format(l2x, l2y))

ln2 = np.array([[1],
                [1]])
ln2x = ln2.shape[0]
ln2y = ln2.shape[1]
print("Rows: {}, Cols: {}".format(ln2x, ln2y))

Rows: 2, Cols: 2
Rows: 2, Cols: 1


In [64]:
# brute force search for if ANY pieces of a given set can fit
hand = p.rand_hand()
count = 0
print(grid)
for h in hand:
    print(h)
    print(np.sum(h))
    x = h.shape[0]
    y = h.shape[1]
    for i in range(10):
        if i+x <= 10:
            for j in range(10):
                if j+y <= 10:
                    ew_sum = np.sum([h, grid[i:i+x, j:j+y]])
                    
                    if ew_sum <= np.sum(h):
                        count += 1
                        print("Count: {}".format(count))
#                         print(ew_sum)
#                         print(grid[i:i+x, j:j+y])

[[1 1 1 0 0 0 1 1 0 1]
 [0 1 0 1 0 1 0 1 0 0]
 [1 1 1 1 0 1 0 1 1 1]
 [1 1 0 0 0 1 1 1 1 0]
 [1 0 0 1 0 1 1 1 1 1]
 [0 0 0 0 1 1 0 0 1 0]
 [1 0 0 1 1 1 0 1 0 1]
 [0 0 0 1 1 0 1 0 0 0]
 [1 1 1 1 1 1 1 1 0 1]
 [0 0 0 0 0 0 1 1 0 0]]
[[1]
 [1]]
2
Count: 1
Count: 2
Count: 3
Count: 4
Count: 5
Count: 6
Count: 7
Count: 8
Count: 9
Count: 10
Count: 11
Count: 12
Count: 13
Count: 14
Count: 15
Count: 16
Count: 17
[[1 1 1 1]]
4
Count: 18
Count: 19
Count: 20
Count: 21
[[1 1]
 [1 1]]
4
Count: 22
Count: 23
Count: 24


In [27]:
grid[1:5,2]

array([0, 1, 0, 0])

In [ ]:
elem_sum = np.sum([p_space[locs[0], locs[1]], grid[locs[0], locs[1]]], axis=0)
                        # print(elem_sum)
                        illegal_count = np.where(elem_sum >= 3)
                        # print(np.shape(illegal_count)[1])

                        if np.shape(illegal_count)[1] == 0:
                            p_space[locs[0], locs[1]] = 0
                            grid[locs[0], locs[1]] = 2
                            # Update score for placed piece
                            score += (np.sum(elem_sum)/2)

In [52]:
np.array([np.random.randint(0,2,10) for _ in range(10)], dtype=int)

array([[1, 0, 0, 1, 0, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 0, 1, 1, 0, 1, 1],
       [0, 1, 1, 1, 0, 0, 1, 1, 0, 0],
       [1, 0, 1, 0, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 1, 0, 1, 1, 1, 0],
       [0, 0, 1, 0, 1, 0, 1, 1, 1, 1],
       [1, 1, 1, 0, 1, 1, 0, 1, 1, 0],
       [0, 1, 1, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 1, 0, 1, 1],
       [1, 0, 0, 1, 0, 1, 0, 1, 0, 0]])

TypeError: list indices must be integers or slices, not tuple

In [63]:
len([])

0